server {
    listen 80; #http/1.1
    listen 443 ssl http2; #http/2
    server_name localhost;

    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

    location /cv1 {
        alias /usr/share/nginx/cv1/;
        index index.html;
    }

    location /cv2 {
        alias /usr/share/nginx/cv2/;
        index index.html;
    }

    location /cv3 {
        alias /usr/share/nginx/cv3/;
        index index_w3.css.html;
    }
}